### PR TITLE
Add main.py

### PR DESCRIPTION
**Pull request by sweeneyde**

### CODE REVIEW

**Comment by Alex7Li** [comment]
You're a hero

**Comment by Alex7Li** [comment]
How do you handle something where you have hundreds of main python scripts that you want to run? Do you need to put them all in the top level directory? It seems really restrictive

**Comment by sweeneyde** [comment]
If you have a folder with an `folder/__main__.py` then you can run `python ./folder`, and I think (hopefully?) that also works for nested packages

**Comment by Alex7Li** [comment]
Oh that's interesting. It still doesn't work to go up a level, though. I tried it in this repo:
```
(base) alex@alex-Laptop:~/git/dennis_help$ python ./dir1
Traceback (most recent call last):
  File "/home/alex/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/alex/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/alex/git/dennis_help/./dir1/__main__.py", line 1, in <module>
    import a
  File "/home/alex/git/dennis_help/./dir1/a.py", line 1, in <module>
    import dir2.b
ModuleNotFoundError: No module named 'dir2'
``

**Comment by sweeneyde** [comment]
idk maybe one of the answers here helps https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path?rq=1

**Comment by Alex7Li** [comment]
I looked around more and I think the only good way is to pip install your own package in an editable state.  https://stackoverflow.com/a/50194143/7830459

I guess the moral of the story is that python really wants files to only be able to access sub directories.

**Comment by sweeneyde** [comment]
yeah I think iv'e seen people append to sys.path so even though it's hacky it's not that uncommon

**Pull request merged**
